SET LED 13
SET DELAY_TIME 500
SET COUNTER 0
SET MAX_COUNT 5

LABEL LOOP
    PRINT "BLINKING: " COUNTER "/" MAX_COUNT ENDL
    GPIO LED ON
    DELAY DELAY_TIME
    GPIO LED OFF
    DELAY DELAY_TIME
    ADD COUNTER COUNTER 1
    IF COUNTER == MAX_COUNT GOTO END
    GOTO LOOP

LABEL END
    PRINT "DONE!" ENDL